import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// import React from 'react'
import { useAuth } from '../contexts/AuthContext';
import { User, Mail, Building, Calendar, Shield } from 'lucide-react';
export function ProfilePage() {
    const { user } = useAuth();
    if (!user) {
        return (_jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8", children: _jsx("div", { className: "text-center", children: _jsx("p", { className: "text-gray-600", children: "Loading profile..." }) }) }));
    }
    return (_jsxs("div", { className: "max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900 mb-2", children: "Profile" }), _jsx("p", { className: "text-gray-600", children: "Manage your account information and preferences" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-8", children: [_jsx("div", { className: "lg:col-span-2", children: _jsxs("div", { className: "card", children: [_jsx("h2", { className: "text-xl font-semibold text-gray-900 mb-6", children: "Personal Information" }), _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx(User, { className: "h-5 w-5 text-gray-400" }), _jsxs("div", { children: [_jsx("div", { className: "text-sm font-medium text-gray-900", children: "Full Name" }), _jsx("div", { className: "text-gray-600", children: user.profile.name || 'Not provided' })] })] }), _jsxs("div", { className: "flex items-center space-x-3", children: [_jsx(Mail, { className: "h-5 w-5 text-gray-400" }), _jsxs("div", { children: [_jsx("div", { className: "text-sm font-medium text-gray-900", children: "Email Address" }), _jsx("div", { className: "text-gray-600", children: user.email })] })] }), user.profile.company && (_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx(Building, { className: "h-5 w-5 text-gray-400" }), _jsxs("div", { children: [_jsx("div", { className: "text-sm font-medium text-gray-900", children: "Company" }), _jsx("div", { className: "text-gray-600", children: user.profile.company })] })] })), _jsxs("div", { className: "flex items-center space-x-3", children: [_jsx(Shield, { className: "h-5 w-5 text-gray-400" }), _jsxs("div", { children: [_jsx("div", { className: "text-sm font-medium text-gray-900", children: "Account Type" }), _jsx("div", { className: "text-gray-600 capitalize", children: user.role })] })] }), _jsxs("div", { className: "flex items-center space-x-3", children: [_jsx(Calendar, { className: "h-5 w-5 text-gray-400" }), _jsxs("div", { children: [_jsx("div", { className: "text-sm font-medium text-gray-900", children: "Member Since" }), _jsx("div", { className: "text-gray-600", children: new Date(user.createdAt).toLocaleDateString() })] })] })] }), _jsx("div", { className: "mt-8 pt-6 border-t border-gray-200", children: _jsx("button", { className: "btn-primary", children: "Edit Profile" }) })] }) }), _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "card", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-4", children: "Account Status" }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600", children: "Status" }), _jsx("span", { className: `px-2 py-1 text-xs font-medium rounded-full ${user.status === 'active'
                                                            ? 'bg-green-100 text-green-800'
                                                            : user.status === 'pending'
                                                                ? 'bg-yellow-100 text-yellow-800'
                                                                : 'bg-red-100 text-red-800'}`, children: user.status })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600", children: "Email Verified" }), _jsx("span", { className: "px-2 py-1 text-xs font-medium rounded-full bg-green-100 text-green-800", children: "Verified" })] })] })] }), user.role === 'partner' && (_jsxs("div", { className: "card", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-4", children: "Partner Status" }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600", children: "Partner Level" }), _jsx("span", { className: "px-2 py-1 text-xs font-medium rounded-full bg-blue-100 text-blue-800", children: "Basic" })] }), _jsxs("div", { className: "text-sm text-gray-600", children: [_jsx("div", { children: "Solutions: 0" }), _jsx("div", { children: "Total Sales: $0" })] })] })] }))] })] })] }));
}
